import type {
  AccountMatch,
  Contact,
  CrmAccount,
  DecisionMemo,
  Event,
  EventCompany,
  EventFact,
  EventScore,
  Evidence,
  Job,
  OutreachDraft,
  RevenueProfile,
  SchruteDemoBundle,
  SourceDocument,
  UnderwritingAssumptions,
} from "./types";

const NOW = Date.parse("2026-06-28T12:00:00.000Z");

export const MOCK_IDS = {
  revenueProfile: "mock_revenue_profile_1",
  event: "mock_event_woc_2026",
  eventSkip: "mock_event_skip_demo",
  sourceDocument: "mock_source_woc_exhibitors",
  eventScore: "mock_event_score_woc",
  decisionMemo: "mock_decision_memo_woc",
} as const;

export const DEFAULT_UNDERWRITING_ASSUMPTIONS: UnderwritingAssumptions = {
  sponsorCost: 25000,
  travelCost: 6000,
  repTimeCost: 4000,
  avgDealSize: 85000,
  meetingToOppRate: 0.35,
  winRate: 0.22,
  riskDiscount: 0.85,
  captureRate: 0.12,
};

const wocSourceUrl =
  "https://www.worldofconcrete.com/en/exhibitor-list.html";

const wocEvidence = (
  quote: string,
  factType: Evidence["factType"] = "exhibitor",
): Evidence => ({
  sourceDocumentId: MOCK_IDS.sourceDocument,
  sourceUrl: wocSourceUrl,
  quote,
  factType,
  confidence: 0.95,
});

export const mockRevenueProfile: RevenueProfile = {
  _id: MOCK_IDS.revenueProfile,
  name: "SafeSite OS",
  industries: [
    "General Contracting",
    "Commercial Construction",
    "Industrial Construction",
    "Heavy Civil",
  ],
  buyerTitles: [
    "VP Safety",
    "Director of EHS",
    "Safety Manager",
    "VP Operations",
    "Project Executive",
  ],
  dealSizeClusters: [
    { label: "Mid-market", min: 40000, max: 120000, count: 18 },
    { label: "Enterprise", min: 120000, max: 350000, count: 6 },
  ],
  geographies: ["US Midwest", "US South", "US West"],
  keywords: ["jobsite safety", "OSHA compliance", "subcontractor management"],
  closedWonPatterns: [
    "Multi-site GCs with subcontractor compliance pain",
    "Industrial contractors with incident reporting gaps",
  ],
  createdAt: NOW - 86400000,
};

export const mockCrmAccounts: CrmAccount[] = [
  {
    _id: "mock_crm_turner",
    revenueProfileId: MOCK_IDS.revenueProfile,
    companyName: "Turner Construction",
    domain: "turnerconstruction.com",
    accountType: "open_opp",
    stage: "Negotiation",
    dealSize: 180000,
    industry: "General Contracting",
    region: "US Northeast",
    buyerTitle: "VP Safety",
    openOppValue: 180000,
    createdAt: NOW - 86400000,
  },
  {
    _id: "mock_crm_skanska",
    revenueProfileId: MOCK_IDS.revenueProfile,
    companyName: "Skanska USA",
    domain: "usa.skanska.com",
    accountType: "open_opp",
    stage: "Discovery",
    dealSize: 95000,
    industry: "Commercial Construction",
    region: "US Northeast",
    buyerTitle: "Director of EHS",
    openOppValue: 95000,
    createdAt: NOW - 86400000,
  },
  {
    _id: "mock_crm_clark",
    revenueProfileId: MOCK_IDS.revenueProfile,
    companyName: "Clark Construction",
    domain: "clarkconstruction.com",
    accountType: "target",
    stage: "Target",
    dealSize: 110000,
    industry: "General Contracting",
    region: "US Mid-Atlantic",
    buyerTitle: "VP Safety",
    createdAt: NOW - 86400000,
  },
  {
    _id: "mock_crm_mortenson",
    revenueProfileId: MOCK_IDS.revenueProfile,
    companyName: "Mortenson",
    domain: "mortenson.com",
    accountType: "closed_won",
    stage: "Closed Won",
    dealSize: 72000,
    industry: "Commercial Construction",
    region: "US Midwest",
    buyerTitle: "Safety Manager",
    createdAt: NOW - 86400000,
  },
  {
    _id: "mock_crm_haskell",
    revenueProfileId: MOCK_IDS.revenueProfile,
    companyName: "The Haskell Company",
    domain: "haskell.com",
    accountType: "target",
    stage: "Target",
    dealSize: 88000,
    industry: "Industrial Construction",
    region: "US South",
    buyerTitle: "Director of EHS",
    createdAt: NOW - 86400000,
  },
  {
    _id: "mock_crm_brasfield",
    revenueProfileId: MOCK_IDS.revenueProfile,
    companyName: "Brasfield & Gorrie",
    domain: "brasfieldgorrie.com",
    accountType: "closed_won",
    stage: "Closed Won",
    dealSize: 65000,
    industry: "General Contracting",
    region: "US South",
    buyerTitle: "VP Operations",
    createdAt: NOW - 86400000,
  },
];

export const mockEvent: Event = {
  _id: MOCK_IDS.event,
  name: "World of Concrete 2026",
  slug: "world-of-concrete-2026",
  startDate: "2026-01-20",
  endDate: "2026-01-22",
  location: "Las Vegas, NV",
  sponsorQuote: 25000,
  revenueProfileId: MOCK_IDS.revenueProfile,
  assumptions: DEFAULT_UNDERWRITING_ASSUMPTIONS,
  createdAt: NOW - 3600000,
};

export const mockSourceDocuments: SourceDocument[] = [
  {
    _id: MOCK_IDS.sourceDocument,
    eventId: MOCK_IDS.event,
    kind: "snapshot",
    url: wocSourceUrl,
    title: "World of Concrete 2026 Exhibitor List (cached snapshot)",
    textContent:
      "Exhibitor List — Booth N1234 Turner Construction ... Booth S4521 Skanska USA ... Booth C1102 Clark Construction ...",
    contentHash: "sha256:mock_woc_exhibitor_snapshot_v1",
    fetchedAt: NOW - 3500000,
  },
];

export const mockEventFacts: EventFact[] = [
  {
    _id: "mock_fact_exhibitor_count",
    eventId: MOCK_IDS.event,
    sourceDocumentId: MOCK_IDS.sourceDocument,
    factType: "exhibitor_list",
    label: "Exhibitor count (partial page)",
    value: "142 exhibitors parsed from cached snapshot",
    quote: "Exhibitor List — searchable directory of exhibiting companies",
    confidence: 0.9,
    createdAt: NOW - 3400000,
  },
];

export const mockEventCompanies: EventCompany[] = [
  {
    _id: "mock_ec_turner",
    eventId: MOCK_IDS.event,
    sourceDocumentId: MOCK_IDS.sourceDocument,
    companyName: "Turner Construction",
    normalizedName: "turner construction",
    domain: "turnerconstruction.com",
    role: "exhibitor",
    boothOrSession: "N1234",
    quote: "Turner Construction — Booth N1234",
    confidence: 0.97,
    createdAt: NOW - 3300000,
  },
  {
    _id: "mock_ec_skanska",
    eventId: MOCK_IDS.event,
    sourceDocumentId: MOCK_IDS.sourceDocument,
    companyName: "Skanska USA",
    normalizedName: "skanska usa",
    domain: "usa.skanska.com",
    role: "exhibitor",
    boothOrSession: "S4521",
    quote: "Skanska USA — Booth S4521",
    confidence: 0.96,
    createdAt: NOW - 3300000,
  },
  {
    _id: "mock_ec_clark",
    eventId: MOCK_IDS.event,
    sourceDocumentId: MOCK_IDS.sourceDocument,
    companyName: "Clark Construction",
    normalizedName: "clark construction",
    domain: "clarkconstruction.com",
    role: "exhibitor",
    boothOrSession: "C1102",
    quote: "Clark Construction — Booth C1102",
    confidence: 0.95,
    createdAt: NOW - 3300000,
  },
  {
    _id: "mock_ec_procore_netnew",
    eventId: MOCK_IDS.event,
    sourceDocumentId: MOCK_IDS.sourceDocument,
    companyName: "BuildRight Materials",
    normalizedName: "buildright materials",
    role: "exhibitor",
    boothOrSession: "W2201",
    quote: "BuildRight Materials — Booth W2201",
    confidence: 0.88,
    createdAt: NOW - 3300000,
  },
];

export const mockAccountMatches: AccountMatch[] = [
  {
    _id: "mock_match_turner",
    eventId: MOCK_IDS.event,
    tier: "tier1_crm",
    crmAccountId: "mock_crm_turner",
    companyName: "Turner Construction",
    domain: "turnerconstruction.com",
    role: "exhibitor",
    boothOrSession: "N1234",
    fitScore: 0.98,
    confidence: 0.97,
    evidence: [wocEvidence("Turner Construction — Booth N1234")],
    matchedOppValue: 180000,
    eventCompanyId: "mock_ec_turner",
    rank: 1,
    createdAt: NOW - 3200000,
  },
  {
    _id: "mock_match_skanska",
    eventId: MOCK_IDS.event,
    tier: "tier1_crm",
    crmAccountId: "mock_crm_skanska",
    companyName: "Skanska USA",
    domain: "usa.skanska.com",
    role: "exhibitor",
    boothOrSession: "S4521",
    fitScore: 0.94,
    confidence: 0.96,
    evidence: [wocEvidence("Skanska USA — Booth S4521")],
    matchedOppValue: 95000,
    eventCompanyId: "mock_ec_skanska",
    rank: 2,
    createdAt: NOW - 3200000,
  },
  {
    _id: "mock_match_clark",
    eventId: MOCK_IDS.event,
    tier: "tier1_crm",
    crmAccountId: "mock_crm_clark",
    companyName: "Clark Construction",
    domain: "clarkconstruction.com",
    role: "exhibitor",
    boothOrSession: "C1102",
    fitScore: 0.91,
    confidence: 0.95,
    evidence: [wocEvidence("Clark Construction — Booth C1102")],
    eventCompanyId: "mock_ec_clark",
    rank: 3,
    createdAt: NOW - 3200000,
  },
  {
    _id: "mock_match_mortenson",
    eventId: MOCK_IDS.event,
    tier: "tier1_crm",
    crmAccountId: "mock_crm_mortenson",
    companyName: "Mortenson",
    domain: "mortenson.com",
    role: "exhibitor",
    boothOrSession: "N8820",
    fitScore: 0.86,
    confidence: 0.82,
    evidence: [wocEvidence("Mortenson — Booth N8820", "exhibitor")],
    rank: 4,
    createdAt: NOW - 3200000,
  },
  {
    _id: "mock_match_haskell",
    eventId: MOCK_IDS.event,
    tier: "tier1_crm",
    crmAccountId: "mock_crm_haskell",
    companyName: "The Haskell Company",
    domain: "haskell.com",
    role: "sponsor",
    boothOrSession: "Gold Sponsor",
    fitScore: 0.84,
    confidence: 0.9,
    evidence: [wocEvidence("The Haskell Company — Gold Sponsor", "sponsor")],
    rank: 5,
    createdAt: NOW - 3200000,
  },
  {
    _id: "mock_match_buildright",
    eventId: MOCK_IDS.event,
    tier: "tier2_icp",
    companyName: "BuildRight Materials",
    role: "exhibitor",
    boothOrSession: "W2201",
    fitScore: 0.78,
    confidence: 0.88,
    evidence: [wocEvidence("BuildRight Materials — Booth W2201")],
    eventCompanyId: "mock_ec_procore_netnew",
    rank: 6,
    createdAt: NOW - 3200000,
  },
];

export const mockEventScore: EventScore = {
  _id: MOCK_IDS.eventScore,
  eventId: MOCK_IDS.event,
  totalEventCost: 35000,
  revenuePerQualifiedMeeting: 5577.5,
  requiredQualifiedMeetings: 7,
  sponsorCap: 12000,
  matchedPipelineValue: 275000,
  tier1MatchCount: 5,
  tier2MatchCount: 1,
  recommendation: "attend",
  subScores: {
    pipelinePresence: 0.88,
    evidenceQuality: 0.92,
    costEfficiency: 0.71,
    icpDensity: 0.76,
  },
  assumptions: DEFAULT_UNDERWRITING_ASSUMPTIONS,
  rationale: [
    "5 Tier-1 CRM accounts confirmed exhibiting with high-confidence source quotes.",
    "$275K matched open pipeline on the floor — booth not required to reach them.",
    "Break-even requires 7 qualified meetings; 2 open opps already present.",
    "Sponsor cap $12K — below quoted $25K booth.",
  ],
  createdAt: NOW - 3000000,
};

export const mockDecisionMemo: DecisionMemo = {
  _id: MOCK_IDS.decisionMemo,
  eventId: MOCK_IDS.event,
  eventScoreId: MOCK_IDS.eventScore,
  headline: "Attend — don't sponsor over $12K",
  verdict: "attend",
  sections: [
    {
      title: "Confirmed pipeline on the floor",
      body: "5 of your CRM accounts — including 2 open deals worth $275K — are confirmed exhibiting at World of Concrete. Evidence is exhibitor-list sourced, not inferred attendance.",
      citations: [wocEvidence("Turner Construction — Booth N1234")],
    },
    {
      title: "Economics",
      body: "All-in cost ~$35K needs 7 qualified meetings to break even. Your accounts are here whether you sponsor or not — send two reps and host a dinner.",
      citations: [],
    },
  ],
  missingEvidence: ["Full exhibitor PDF not yet ingested — using cached snapshot."],
  createdAt: NOW - 2900000,
};

export const mockContacts: Contact[] = [
  {
    _id: "mock_contact_turner",
    accountMatchId: "mock_match_turner",
    eventId: MOCK_IDS.event,
    fullName: "Jane Doe",
    title: "VP Safety",
    email: "jane.doe@turnerconstruction.com",
    verification: "verified",
    createdAt: NOW - 2800000,
  },
];

export const mockOutreachDrafts: OutreachDraft[] = [
  {
    _id: "mock_outreach_turner",
    accountMatchId: "mock_match_turner",
    contactId: "mock_contact_turner",
    eventId: MOCK_IDS.event,
    subject: "Quick coffee at World of Concrete?",
    body: "Hi Jane — saw Turner is exhibiting at World of Concrete (Booth N1234). We're working through safety workflows with several GCs and would love 20 minutes before the floor gets loud. Open to Tue AM?",
    tone: "direct",
    createdAt: NOW - 2700000,
  },
];

export const mockJobs: Job[] = [
  {
    _id: "mock_job_ingest",
    eventId: MOCK_IDS.event,
    step: "ingest",
    status: "completed",
    message: "Cached exhibitor snapshot loaded",
    progress: 100,
    updatedAt: NOW - 3500000,
  },
  {
    _id: "mock_job_extract",
    eventId: MOCK_IDS.event,
    step: "extract",
    status: "completed",
    message: "142 companies extracted",
    progress: 100,
    updatedAt: NOW - 3400000,
  },
  {
    _id: "mock_job_match",
    eventId: MOCK_IDS.event,
    step: "match",
    status: "completed",
    message: "6 account matches ranked",
    progress: 100,
    updatedAt: NOW - 3200000,
  },
  {
    _id: "mock_job_score",
    eventId: MOCK_IDS.event,
    step: "score",
    status: "completed",
    progress: 100,
    updatedAt: NOW - 3000000,
  },
  {
    _id: "mock_job_memo",
    eventId: MOCK_IDS.event,
    step: "memo",
    status: "completed",
    progress: 100,
    updatedAt: NOW - 2900000,
  },
  {
    _id: "mock_job_enrich",
    eventId: MOCK_IDS.event,
    step: "enrich",
    status: "running",
    message: "Fiber enrichment (sidecar)",
    progress: 40,
    updatedAt: NOW - 2800000,
  },
];

export const mockDemoBundle: SchruteDemoBundle = {
  revenueProfile: mockRevenueProfile,
  crmAccounts: mockCrmAccounts,
  event: mockEvent,
  sourceDocuments: mockSourceDocuments,
  eventFacts: mockEventFacts,
  eventCompanies: mockEventCompanies,
  accountMatches: mockAccountMatches,
  eventScore: mockEventScore,
  decisionMemo: mockDecisionMemo,
  contacts: mockContacts,
  outreachDrafts: mockOutreachDrafts,
  jobs: mockJobs,
};

export const mockSkipEventScore: EventScore = {
  _id: "mock_event_score_skip",
  eventId: MOCK_IDS.eventSkip,
  totalEventCost: 32000,
  revenuePerQualifiedMeeting: 5577.5,
  requiredQualifiedMeetings: 6,
  sponsorCap: 0,
  matchedPipelineValue: 45000,
  tier1MatchCount: 1,
  tier2MatchCount: 2,
  recommendation: "skip",
  subScores: {
    pipelinePresence: 0.22,
    evidenceQuality: 0.65,
    costEfficiency: 0.18,
    icpDensity: 0.3,
  },
  assumptions: DEFAULT_UNDERWRITING_ASSUMPTIONS,
  rationale: [
    "Only 1 Tier-1 CRM account with weak exhibitor evidence.",
    "Matched pipeline $45K — insufficient to justify $32K all-in cost.",
    "High logo density, low pipeline concentration — skip unless competitor research.",
  ],
  createdAt: NOW - 1000000,
};

export const mockAccountMatchesForEnrichment: AccountMatch[] =
  mockAccountMatches.filter((m) => m.tier === "tier1_crm").slice(0, 3);
